{
 "title": "Cisco-IOS-XE gRPC monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Cisco IOS-XE gRPC CPU Monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_source]]-iosd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
     "select": [
      [
       { "params": [ "five_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco IOS-XE gRPC Memory Utilization Monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_source]]-iosd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
     "query": "SELECT mean(\"used_memory\")*100/mean(\"total_memory\") FROM \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\" WHERE (\"name\" = 'Processor') AND $timeFilter GROUP BY time($__interval), \"source\" fill(none)",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Processor" }
     ]
    }
   ]
  },
  {
   "title": "Cisco IOS-XE gRPC Interface RX rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "[[tag_source]]-[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "query": "SELECT derivative(mean(\"in_octets\"), 1s)*8 FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE $timeFilter GROUP BY time($__interval), \"name\", \"source\" fill(none)",
     "select": [
      [
       { "params": [ "in_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco IOS-XE gRPC Interface TX rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "[[tag_source]]-[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics",
     "query": "SELECT derivative(mean(\"out_octets\"), 1s)*8 FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\" WHERE $timeFilter GROUP BY time($__interval), \"name\", \"source\" fill(none)",
     "select": [
      [
       { "params": [ "out_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  }
 ]
}