{
 "title": "Cisco-IOS-XE SNMP monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Cisco IOS-XE SNMP CPU 5s Total Monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]-platform",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "select": [
      [
       { "params": [ "CPUTotal5sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-iosd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "select": [
      [
       { "params": [ "CPUTotal5sec-iosd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco IOS-XE SNMP Memory Utilization Monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]-platform",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "query": "SELECT mean(\"MemoryUsed\")*100/(mean(\"MemoryUsed\")+mean(\"MemoryFree\")) FROM \"CSR1000v_Snmp_v2c\" WHERE time >= now() - 15m GROUP BY time(500ms), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "MemoryFree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "MemoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-iosd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "query": "SELECT mean(\"MemoryUsed-iosd\")*100/(mean(\"MemoryUsed-iosd\")+mean(\"MemoryFree-iosd\")) FROM \"CSR1000v_Snmp_v2c\" WHERE time >= now() - 15m GROUP BY time(500ms), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "MemoryFree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "MemoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco IOS-XE SNMP Interface RX rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifInOctets-G1\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifInOctets-G3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifInOctets-G2\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifInOctets-G3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifInOctets-G3\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifInOctets-G3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco IOS-XE SNMP G3 Interface TX rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifOutOctets-G1\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifOutOctets-G3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifOutOctets-G2\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifOutOctets-G3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CSR1000v_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifOutOctets-G3\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifOutOctets-G3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  }
 ]
}