{
 "title": "Cisco ASA SNMP monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Cisco ASA SNMP CPU 1m Total Monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "select": [
      [
       { "params": [ "CPUTotal1min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco ASA SNMP Memory Utilization Monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT mean(\"MemoryFree\")*100/(mean(\"MemoryFree\")+mean(\"MemoryUsed\")) FROM \"ASA_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "MemoryFree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "MemoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco ASA SNMP Interface RX rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet0/0-Outside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifInOctets-G1\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifInOctets-G0-Outside" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet0/1-Inside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifInOctets-G2\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifInOctets-G1-Inside" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco ASA SNMP Interface RX rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet0/0-Outside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifInOctets-G1\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifInOctets-G0-Outside" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-GigabitEthernet0/1-Inside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifInOctets-G2\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "ifInOctets-G1-Inside" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cisco ASA VPN ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "[[tag_agent_host]]-TotalIPSec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifOutOctets-G1\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "TotalIPSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-L2LIPSec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifOutOctets-G2\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "L2LIPSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-Anyconnect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifOutOctets-G2\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "AnyConnectVPN" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_agent_host]]-WebVPN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ASA_Snmp_v2c",
     "query": "SELECT derivative(mean(\"ifOutOctets-G2\"), 1s)*8 FROM \"CSR1000v_Snmp_v2c\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "WebVPN" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  }
 ]
}