filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "qytang-asa-%{+yyyy.MM.dd}"

setup.kibana.host: "http://kibana:5601"
setup.template.name: "qytang-asa"
setup.template.pattern: "qytang-asa-*"
setup.ilm.enabled: false